name: mscthesis
channels:
  - anaconda
  - conda-forge
  - bioconda
  - pytorch
  - r
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - annotated-types=0.6.0=pyhd8ed1ab_0
  - anyio=3.7.1=pyhd8ed1ab_0
  - asttokens=2.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli=1.0.9=he6710b0_2
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.20.1=hd590300_0
  - ca-certificates=2023.08.22=h06a4308_0
  - cairo=1.16.0=hcf35c78_1003
  - catalogue=2.0.7=py38h06a4308_0
  - certifi=2023.11.17=py38h06a4308_0
  - charset-normalizer=3.3.0=pyhd8ed1ab_0
  - click=8.1.7=py38h06a4308_0
  - cloudpathlib=0.16.0=pyhd8ed1ab_0
  - cmake=3.27.4=hcfe8598_4
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - confection=0.1.4=py38hb563948_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cudatoolkit=11.1.1=hb139c0e_13
  - cycler=0.11.0=pyhd3eb1b0_0
  - cymem=2.0.6=py38h295c915_0
  - cython-blis=0.7.10=py38h7f0c24c_2
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.6=hfdff14a_1
  - debugpy=1.8.0=py38h17151c0_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - distro=1.8.0=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - ffmpeg=4.3.2=h37c90e5_3
  - filelock=3.9.0=py38h06a4308_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h267a509_2
  - fsspec=2023.9.2=py38h06a4308_0
  - gettext=0.21.1=h27087fc_0
  - glib=2.66.3=h58526e2_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=py38h578d9bd_0
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - hoomd=2.9.7=gpu_py38h7668a90_1
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.2=pyhd8ed1ab_0
  - httpx=0.25.1=pyhd8ed1ab_0
  - huggingface_hub=0.17.3=py38h06a4308_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=64.2=he1b5a44_1
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.1.0=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.25.2=pyh2140261_0
  - ipython=8.12.2=pyh41d4057_0
  - jasper=1.900.1=h07fcdf6_1006
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.2.0=py38h06a4308_0
  - jpeg=9e=h0b41bf4_3
  - jupyter_client=8.3.1=pyhd8ed1ab_0
  - jupyter_core=5.3.2=py38h578d9bd_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py38h6a678d5_0
  - krb5=1.20.1=hf9c8cef_0
  - lame=3.100=h166bdaf_1003
  - langcodes=3.3.0=pyhd3eb1b0_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=12_linux64_mkl
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=9.0.1=default_hb4e5071_5
  - libcurl=8.2.1=h91b91d3_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libglib=2.66.3=hbe7bbb4_0
  - libgomp=13.2.0=h807b86a_2
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm9=9.0.1=default_hc23dcda_7
  - libnghttp2=1.52.0=ha637b67_1
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libopencv=4.5.2=py38hcdf9bf1_0
  - libpng=1.6.39=h753d276_0
  - libprotobuf=3.15.8=h780b84a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.43.0=h2797004_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libtiff=4.2.0=hf544144_3
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.46.0=hd590300_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=8.0.1=hc9558a2_0
  - markdown-it-py=2.2.0=py38h06a4308_1
  - markupsafe=2.1.5=py38h01eb140_0
  - matplotlib=3.7.2=py38h06a4308_0
  - matplotlib-base=3.7.2=py38h1128e8f_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.0=py38h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munkres=1.1.4=py_0
  - murmurhash=1.0.7=py38h295c915_0
  - ncurses=6.4=hcb278e6_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - networkx=3.1=pyhd8ed1ab_0
  - nltk=3.8.1=py38h06a4308_0
  - nspr=4.35=h27087fc_0
  - nss=3.94=h1d7d5a4_0
  - numpy=1.24.4=py38h59b608b_0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.5.2=py38h578d9bd_0
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.0.3=py38h01efb38_1
  - parso=0.8.3=pyhd8ed1ab_0
  - pathy=0.10.1=py38h06a4308_0
  - pcre=8.45=h9c3ff4c_0
  - pdf2image=1.16.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.38.0=h516909a_1003
  - platformdirs=3.11.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyhd8ed1ab_4
  - preshed=3.0.6=py38h295c915_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py38h01eb140_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-opencv=4.5.2=py38hd0cf306_0
  - pydantic=2.5.1=pyhd8ed1ab_0
  - pydantic-core=2.14.3=py38h0cc4f7c_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyqt=5.12.3=py38ha8c2ead_3
  - pysocks=1.7.1=pyha2e5f31_6
  - pytesseract=0.3.12=pyhd8ed1ab_0
  - python=3.8.0=h357f687_5
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=2.2.1=py3.8_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py38h01eb140_1
  - pyzmq=25.1.1=py38h509eb50_1
  - qt=5.12.5=hd8c4c69_1
  - readline=8.2=h8228510_1
  - regex=2023.10.3=py38h5eee18b_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rhash=1.4.4=hd590300_0
  - rich=13.3.5=py38h06a4308_0
  - sacremoses=0.0.43=pyhd3eb1b0_0
  - scikit-learn=1.3.0=py38h1128e8f_0
  - scipy=1.10.1=py38h59b608b_3
  - seaborn=0.12.2=py38h06a4308_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - shellingham=1.5.0=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - smart_open=5.2.1=py38h06a4308_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - spacy=3.7.3=py38hae673b5_0
  - spacy-legacy=3.0.12=py38h06a4308_0
  - spacy-loggers=1.0.4=py38h06a4308_0
  - sqlite=3.43.0=h2c6b66d_0
  - srsly=2.4.8=py38h6a678d5_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=pyh04b8f61_3
  - tbb=2021.8.0=hdb19cb5_0
  - thinc=8.2.2=py38hae673b5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.13=h2797004_0
  - tokenizers=0.10.3=py38hb317417_1
  - torchaudio=2.2.1=py38_cpu
  - torchvision=0.15.2=cpu_py38h83e0c9b_0
  - tornado=6.3.3=py38h01eb140_1
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.11.2=pyhd8ed1ab_0
  - transformers=4.6.1=pyhd8ed1ab_0
  - typer=0.9.0=py38h06a4308_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - urllib3=2.0.6=pyhd8ed1ab_0
  - wasabi=0.9.1=py38h06a4308_0
  - wcwidth=0.2.8=pyhd8ed1ab_0
  - weasel=0.3.4=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - wordcloud=1.9.2=py38h5eee18b_0
  - x264=1!161.3030=h7f98852_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - astroid==2.5
      - async-timeout==4.0.3
      - attrs==23.1.0
      - beautifulsoup4==4.12.2
      - bibtexparser==1.4.1
      - bitarray==2.8.2
      - cffi==1.16.0
      - chardet==5.2.0
      - crossref-commons==0.0.7
      - cryptography==41.0.7
      - en-core-web-sm==3.7.1
      - frozenlist==1.4.0
      - future==0.18.3
      - htmlparser==0.0.2
      - idna==2.10
      - isort==5.12.0
      - lazy-object-proxy==1.9.0
      - mccabe==0.6.1
      - multidict==6.0.4
      - openai==0.28.1
      - pdfminer-six==20231228
      - pillow==9.5.0
      - pychainedproxy==1.2
      - pycparser==2.21
      - pycryptodome==3.19.0
      - pylint==2.7.1
      - pymupdf==1.23.4
      - pymupdfb==1.23.3
      - pypaperbot==1.2.2
      - pyparsing==3.1.1
      - pypdf2==2.12.1
      - pyqt5-sip==4.19.18
      - pyqtchart==5.12
      - pyqtwebengine==5.12.1
      - ratelimit==2.2.1
      - soupsieve==2.5
      - toml==0.10.2
      - wrapt==1.12.1
      - yarl==1.9.2
prefix: /home/potatosalad/anaconda3/envs/mscthesis
